name: merge dev
on:
  push:
    branches:
      - dev
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge origin dev
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git pull --unshallow
          # 设置上游仓库
          # git remote add upstream https://github.com/upstream/upstream.git
          # git fetch upstream
          git checkout -t origin/main
          git branch -a
          git merge dev --no-ff
          git log
          git push origin main
