name: merge dev
on:
  push:
    branches:
      - dev
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
        ref: main
      - name: Merge origin dev
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          date > generated.txt
          git add .
          git commit -m "generated"
          git push
          # git pull --unshallow
          git branch -a
          # git fetch
          # git branch -a
          # git checkout -t origin/main
          # git merge dev --no-ff
          # echo $(date +%F%n%T) > demo.txt
          # git push origin main
