name: merge dev
on:
  push:
    branches:
      - dev
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     node-version: "16"
      - name: Merge origin dev
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git remote add origin https://github.com/JQiue/action-demo.git
          # git pull --unshallow
          git branch -a
          git fetch
          git branch -a
          git checkout -t origin/main
          git merge dev --no-ff
          git push origin main
