name: deplay
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "14"
      - name: Write SSH keys
        run: |
         install -m 600 -D /dev/null ~/.ssh/id_rsa
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         ssh-keyscan -H 1.117.21.196 > ~/.ssh/known_hosts
#       - name: Create SSH key
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$SSH_PRIVATE_KEY" > ../private.key
#           sudo chmod 600 ../private.key
#           echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
#         shell: bash
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
#           SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
#           SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: link remote
        run: ssh root@1.117.21.196
