name: deplay
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "14"
      - name: Write SSH keys
        run: |
         install -m 600 -D /dev/null ~/.ssh/id_rsa
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         ssh-keyscan -H 1.117.21.196 > ~/.ssh/known_hosts
      - name: link remote
        run: ssh -T root@1.117.21.196
      - name: link remote
        run: ls -a
      - run: ls
      - run: pwd
      - run: cd aurora | ls
