name: deplay
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: ping rpapi.jinqiu.wang
      - run: ping rpapi.jinsqiu.wang
