name: deplay
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
         with:
           node-version: "14"
       - name: Write SSH keys
         run: |
           node -v
       - name: link remote
         run: ssh -T root@1.117.21.196 | pwd
       - run: pwd

