name: Merge dev
on:
  push:
    branches:
      - dev
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Merge origin dev
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git pull --unshallow
          git fetch
          git checkout -t origin/main
          git merge dev --no-ff
          git push origin main
          git push --delete origin dev
